// USE COMMON ACTION TYPES FILE TO AVOID MISTAKE
// GET ACTIVITIES

export const GET_ACTIVITIES_REQUEST = "GET_ACTIVITIES_REQUEST";
export const GET_ACTIVITIES_FAILURE = "GET_ACTIVITIES_FAILURE";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";




export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_FAILURE = "GET_TEST_FAILURE";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";