// USE COMMON ACTION TYPES FILE TO AVOID MISTAKE
// GET ACTIVITIES

export const GET_ACTIVITIES_REQUEST = "GET_ACTIVITIES_REQUEST";
export const GET_ACTIVITIES_FAILURE = "GET_ACTIVITIES_FAILURE";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";


export const POST_REGISTER_USER_REQUEST = "POST_REGISTER_USER_REQUEST";
export const POST_REGISTER_USER_FAILURE = "POST_REGISTER_USER_FAILURE";
export const POST_REGISTER_USER_SUCCESS = "POST_REGISTER_USER_SUCCESS";

export const POST_LOGIN_USER_REQUEST = "POST_LOGIN_USER_REQUEST";
export const POST_LOGIN_USER_FAILURE = "POST_LOGIN_USER_FAILURE";
export const POST_LOGIN_USER_SUCCESS = "POST_LOGIN_USER_SUCCESS";

export const POST_LOGIN_OTP_REQUEST = "POST_LOGIN_OTP_REQUEST";
export const POST_LOGIN_OTP_FAILURE = "POST_LOGIN_OTP_FAILURE";
export const POST_LOGIN_OTP_SUCCESS = "POST_LOGIN_OTP_SUCCESS";

export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_FAILURE = "GET_TEST_FAILURE";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
