// USE COMMON ACTION TYPES FILE TO AVOID MISTAKE
// GET ACTIVITIES

export const GET_ACTIVITIES_REQUEST = "GET_ACTIVITIES_REQUEST";
export const GET_ACTIVITIES_FAILURE = "GET_ACTIVITIES_FAILURE";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
